apiVersion: v1
kind: Service
metadata:
  name: angelina-controller
  namespace: bio-system
spec:
  ports:
  - name: socket
    port: 6300
    protocol: UDP
    targetPort: 6300
  - name: http
    port: 6300
    protocol: TCP
    targetPort: 6300
  selector:
    app: angelina-controller
