apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: angelina-controller
  namespace: bio-system
  labels:
    app: angelina-controller
spec:
  replicas: 1
  selector:
    matchLabels:
       app: angelina-controller
  template:
    metadata:
      labels:
        app: angelina-controller
    spec:
      containers:
      - name: angelina-controller
        image: happy365/angelina-controller:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0m"
            memory: "0Mi"
          requests:
            cpu: "0m"
            memory: "0Mi"
        env:
        - name: ANGELINA_REDIS_ADDR
          value: angelina-redis
        - name: ANGELINA_REDIS_PORT
          value: "6380"
        - name: ANGELINA_SERVER
          value: ":6300"
        - name: ANGELINA_CONTROLLER_ENTRY
          value: "angelina-controller:6300"
        - name: NAMESPACE
          value: "bio-system"
        - name: START_CMD
          value: "rundoc.sh"
        - name: GLUSTERFS_ENDPOINT
          value: "glusterfs-cluster"
        - name: GLUSTERFS_DATA_VOLUME
          value: "data-volume"
        - name: GLUSTERFS_REFER_VOLUME
          value: "refer-volume"
        - name: ANGELINA_QUOTA
          value: "compute-resources"
        - name: KUBER_APISERVER
          value: "https://10.61.0.160:6443"
        - name: SMTP_ENABLED
          value: "false"
        - name: SMTP_SERVER
          value: ""
        - name: SMTP_SERVER_PORT
          value: ""
        - name: EMAIL_TO
          value: ""
        - name: EMAIL_SMTP_USER
          value: ""
        - name: EMAIL_SMTP_PASS
          value: ""
        - name: EMAIL_SEND_INTERVAL
          value: "30"
        ports:
        - containerPort: 6300
          protocol: UDP
        - containerPort: 6300
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /mnt/data
        - name: refer
          mountPath: /mnt/refer 
      volumes:
      - name: data
        glusterfs:
          endpoints: glusterfs-cluster
          path: data-volume
          readOnly: false   
      - name: refer
        glusterfs:
          endpoints: glusterfs-cluster
          path: refer-volume
          readOnly: true  
