apiVersion: v1
kind: Service
metadata:
  name: angelina-redis
  namespace: bio-system
spec:
  type: NodePort
  ports:
  - port: 6380
    targetPort: 6379
    nodePort: 31000
  selector:
    app: angelina-redis
